branches:
  only:
    - master

dist: trusty
sudo: false

language: ruby

rvm:
  2.4.1

addons:
  apt:
    sources:
      - sourceline: 'ppa:jonathonf/python-3.5'
    packages:
      - python3.5
      - python3-pip

before_install:
  - export PATH=$HOME/.local/bin:$PATH
  - python3.5 -m pip -V
  - python3.5 -m pip install --upgrade pip --user `whoami`
  - python3.5 -m pip -V
  - python3.5 -m pip install https://github.com/juancarlospaco/css-html-js-minify/archive/master.tar.gz --user `whoami`
  - compgen -c css_html_js_minify
  - whereis css_html_js_minify
  - wget -c https://github.com/juancarlospaco/css-html-js-minify/archive/master.tar.gz -O css-html-js-minify.tar.gz
  - tar css-html-js-minify.tar.gz
  - cd css-html-js-minify
  - python3.5 setup.py install
  - cd ../

before_script:
  - chmod +x ./script/deploy.sh

script:
  - bash ./script/deploy.sh

exclude: [vendor]
