branches:
  only:
    - master

dist: trusty
sudo: false

language: node_js

node_js:
  - "8"

addons:
  apt:
    sources:
      - sourceline: 'ppa:rael-gc/rvm'
    packages:
      - rvm

env:
  global:
    - PATH=$HOME/.local/bin:$PATH

before_install:
  - rvm use 2.4 --default --install
  - gem update
  - ruby --version
  - rvm --version
  - bundle --version
  - gem --version
  - bundle install

before_script:
  - chmod +x ./script/deploy.sh

script:
  - bash ./script/deploy.sh

exclude: [vendor]
