branches:
  only:
    - master

dist: trusty
sudo: false

language: node_js

node_js:
  - "8"

addons:
  apt:
    sources:
      - sourceline: 'ppa:rael-gc/rvm'
    packages:
      - rvm

env:
  global:
    - PATH=$HOME/.local/bin:$PATH
    - GH_REPO=https://${GH_TOKEN}@github.com/SimCMinMax/herodamage.git
    - GH_SOURCE_BRANCH=master
    - GH_RAW_BRANCH=gh-pages-raw
    - GH_TARGET_BRANCH=gh-pages-wip
    - JEKYLL_ENV=production
    # The number of file changes required to deploy, put the number of files generated on build + 1
    - DEPLOY_THRESHOLD=4

before_install:
  - rvm use 2.4 --default --install --binary --fuzzy
  - gem update
  - ruby --version
  - rvm --version
  - bundle --version
  - gem --version
  - bundle install

before_script:
  - chmod +x ./script/ci/generate
  - chmod +x ./script/ci/build
  - chmod +x ./script/ci/deploy
  - ./script/ci/generate

script:
  - ./script/ci/build
  - ./script/ci/deploy

exclude: [vendor]
