branches:
  only:
    - master

dist: trusty
sudo: false

language: ruby

rvm:
  2.4.1

addons:
  apt:
    sources:
      - sourceline: 'ppa:jonathonf/python-3.5'
    packages:
      - python3.5
      - python3-pip

before_install:
  - compgen -c python
  - export PATH=$HOME/.local/bin:$PATH
  - pip3.5 install css-html-js-minify --user `whoami`
  - python3 -V
  - python3.5 -V
  - python3.5 -m pip -V
  - pip3 -V
  - pip3.5 -V
  - python3.5 -m pip install css-html-js-minify --user `whoami`

before_script:
  - chmod +x ./script/deploy.sh

script:
  - bash ./script/deploy.sh

exclude: [vendor]
