branches:
  only:
    - master

dist: trusty
sudo: false

language: ruby

rvm:
  2.4.1

addons:
  apt:
    sources:
      - sourceline: 'ppa:jonathonf/python-3.5'
    packages:
      - python3.5
      - python3-pip

before_install:
  # Needed to do pip install
  - export PATH=$HOME/.local/bin:$PATH
  # Upgrade pip from 1.5.4 -> 9.0.1+
  - python3.5 -m pip install --upgrade pip --user `whoami`
  - python3.5 -m pip install https://github.com/juancarlospaco/css-html-js-minify/archive/master.tar.gz --user `whoami`
  - wget -c https://github.com/juancarlospaco/css-html-js-minify/archive/master.tar.gz -O css-html-js-minify.tar.gz
  - tar xvf css-html-js-minify.tar.gz

before_script:
  - chmod +x ./script/deploy.sh

script:
  - bash ./script/deploy.sh

exclude: [vendor]
