branches:
  only:
    - master

dist: trusty
sudo: required

language: ruby

rvm:
  2.4.1

before_install:
  - sudo add-apt-repository ppa:jonathonf/python-3.5
  - sudo apt-get update -q
  - sudo apt-get install python3.5 -y
  - sudo apt-get install python3-pip -y
  - sudo pip3 install css-html-js-minify
  - python3 -V
  - pip3 -V

before_script:
  - chmod +x ./script/deploy.sh

script:
  - bash ./script/deploy.sh

exclude: [vendor]
