branches:
  only:
  - master
sudo: false
language: ruby
rvm:
- 2.4.1
before_script:
- chmod +x ./script/cibuild
script: ./script/cibuild
exclude: [vendor]

env:
  global:
    secure: "xUMV40A5o9qKWC8Cbgi51A"
