name: Hero Damage
title: Hero Damage
description: Hero Damage TC Data Collection Site
url: https://www.herodamage.com
encoding: utf-8
timezone: Europe/Paris

sass:
  sass_dir: _sass
  style: compressed

collections:
  # Until we got Jekyll 3.7.0, this is gonna be a bit a mess for collections
  # Since they have to be in the root folder
  # About
  about:
    output: true
    permalink: /about/:name
  # Simulations
  death_knight:
    output: true
    permalink: /death-knight/:name
  death_knight-combinations:
    output: true
    permalink: /death-knight/combinations/:name
  death_knight-relics:
    output: true
    permalink: /death-knight/relics/:name
  death_knight-trinkets:
    output: true
    permalink: /death-knight/trinkets/:name
  demon_hunter:
    output: true
    permalink: /demon-hunter/:name
  demon_hunter-combinations:
    output: true
    permalink: /demon-hunter/combinations/:name
  demon_hunter-relics:
    output: true
    permalink: /demon-hunter/relics/:name
  demon_hunter-trinkets:
    output: true
    permalink: /demon-hunter/trinkets/:name
  druid:
    output: true
    permalink: /druid/:name
  druid-combinations:
    output: true
    permalink: /druid/combinations/:name
  druid-relics:
    output: true
    permalink: /druid/relics/:name
  druid-trinkets:
    output: true
    permalink: /druid/trinkets/:name
  hunter:
    output: true
    permalink: /hunter/:name
  hunter-combinations:
    output: true
    permalink: /hunter/combinations/:name
  hunter-relics:
    output: true
    permalink: /hunter/relics/:name
  hunter-trinkets:
    output: true
    permalink: /hunter/trinkets/:name
  mage:
    output: true
    permalink: /mage/:name
  mage-combinations:
    output: true
    permalink: /mage/combinations/:name
  mage-relics:
    output: true
    permalink: /mage/relics/:name
  mage-trinkets:
    output: true
    permalink: /mage/trinkets/:name
  monk:
    output: true
    permalink: /monk/:name
  monk-combinations:
    output: true
    permalink: /monk/combinations/:name
  monk-relics:
    output: true
    permalink: /monk/relics/:name
  monk-trinkets:
    output: true
    permalink: /monk/trinkets/:name
  paladin:
    output: true
    permalink: /paladin/:name
  paladin-combinations:
    output: true
    permalink: /paladin/combinations/:name
  paladin-relics:
    output: true
    permalink: /paladin/relics/:name
  paladin-trinkets:
    output: true
    permalink: /paladin/trinkets/:name
  priest:
    output: true
    permalink: /priest/:name
  priest-combinations:
    output: true
    permalink: /priest/combinations/:name
  priest-relics:
    output: true
    permalink: /priest/relics/:name
  priest-trinkets:
    output: true
    permalink: /priest/trinkets/:name
  rogue:
    output: true
    permalink: /rogue/:name
  rogue-combinations:
    output: true
    permalink: /rogue/combinations/:name
  rogue-relics:
    output: true
    permalink: /rogue/relics/:name
  rogue-trinkets:
    output: true
    permalink: /rogue/trinkets/:name
  shaman:
    output: true
    permalink: /shaman/:name
  shaman-combinations:
    output: true
    permalink: /shaman/combinations/:name
  shaman-relics:
    output: true
    permalink: /shaman/relics/:name
  shaman-trinkets:
    output: true
    permalink: /shaman/trinkets/:name
  warlock:
    output: true
    permalink: /warlock/:name
  warlock-combinations:
    output: true
    permalink: /warlock/combinations/:name
  warlock-relics:
    output: true
    permalink: /warlock/relics/:name
  warlock-trinkets:
    output: true
    permalink: /warlock/trinkets/:name
  warrior:
    output: true
    permalink: /warrior/:name
  warrior-combinations:
    output: true
    permalink: /warrior/combinations/:name
  warrior-relics:
    output: true
    permalink: /warrior/relics/:name
  warrior-trinkets:
    output: true
    permalink: /warrior/trinkets/:name


defaults:
  -
    scope:
      path: "" # An empty string here means all files in the project
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "death_knight"
    values:
      layout: "class-index"
      wow_class: "death_knight"
  -
    scope:
      path: ""
      type: "death_knight-combinations"
    values:
      layout: "combinations"
      wow_class: "death_knight"
  -
    scope:
      path: ""
      type: "death_knight-relics"
    values:
      layout: "relics"
      wow_class: "death_knight"
      chart_class: "full-height"
      num_ilevel_values: 20
  -
    scope:
      path: ""
      type: "death_knight-trinkets"
    values:
      layout: "trinkets"
      wow_class: "death_knight"
      chart_class: "full-height"
  -
    scope:
      path: ""
      type: "demon_hunter"
    values:
      layout: "class-index"
      wow_class: "demon_hunter"
  -
    scope:
      path: ""
      type: "demon_hunter-combinations"
    values:
      layout: "combinations"
      wow_class: "demon_hunter"
  -
    scope:
      path: ""
      type: "demon_hunter-relics"
    values:
      layout: "relics"
      wow_class: "demon_hunter"
      chart_class: "full-height"
      num_ilevel_values: 20
  -
    scope:
      path: ""
      type: "demon_hunter-trinkets"
    values:
      layout: "trinkets"
      wow_class: "demon_hunter"
      chart_class: "full-height"
  -
    scope:
      path: ""
      type: "druid"
    values:
      layout: "class-index"
      wow_class: "druid"
  -
    scope:
      path: ""
      type: "druid-combinations"
    values:
      layout: "combinations"
      wow_class: "druid"
  -
    scope:
      path: ""
      type: "druid-relics"
    values:
      layout: "relics"
      wow_class: "druid"
      chart_class: "full-height"
      num_ilevel_values: 20
  -
    scope:
      path: ""
      type: "druid-trinkets"
    values:
      layout: "trinkets"
      wow_class: "druid"
      chart_class: "full-height"
  -
    scope:
      path: ""
      type: "hunter"
    values:
      layout: "class-index"
      wow_class: "hunter"
  -
    scope:
      path: ""
      type: "hunter-combinations"
    values:
      layout: "combinations"
      wow_class: "hunter"
  -
    scope:
      path: ""
      type: "hunter-relics"
    values:
      layout: "relics"
      wow_class: "hunter"
      chart_class: "full-height"
      num_ilevel_values: 20
  -
    scope:
      path: ""
      type: "hunter-trinkets"
    values:
      layout: "trinkets"
      wow_class: "hunter"
      chart_class: "full-height"
  -
    scope:
      path: ""
      type: "mage"
    values:
      layout: "class-index"
      wow_class: "mage"
  -
    scope:
      path: ""
      type: "mage-combinations"
    values:
      layout: "combinations"
      wow_class: "mage"
  -
    scope:
      path: ""
      type: "mage-relics"
    values:
      layout: "relics"
      wow_class: "mage"
      chart_class: "full-height"
      num_ilevel_values: 20
  -
    scope:
      path: ""
      type: "mage-trinkets"
    values:
      layout: "trinkets"
      wow_class: "mage"
      chart_class: "full-height"
  -
    scope:
      path: ""
      type: "monk"
    values:
      layout: "class-index"
      wow_class: "monk"
  -
    scope:
      path: ""
      type: "monk-combinations"
    values:
      layout: "combinations"
      wow_class: "monk"
  -
    scope:
      path: ""
      type: "monk-relics"
    values:
      layout: "relics"
      wow_class: "monk"
      chart_class: "full-height"
      num_ilevel_values: 20
  -
    scope:
      path: ""
      type: "monk-trinkets"
    values:
      layout: "trinkets"
      wow_class: "monk"
      chart_class: "full-height"
  -
    scope:
      path: ""
      type: "paladin"
    values:
      layout: "class-index"
      wow_class: "paladin"
  -
    scope:
      path: ""
      type: "paladin-combinations"
    values:
      layout: "combinations"
      wow_class: "paladin"
  -
    scope:
      path: ""
      type: "paladin-relics"
    values:
      layout: "relics"
      wow_class: "paladin"
      chart_class: "full-height"
      num_ilevel_values: 20
  -
    scope:
      path: ""
      type: "paladin-trinkets"
    values:
      layout: "trinkets"
      wow_class: "paladin"
      chart_class: "full-height"
  -
    scope:
      path: ""
      type: "priest"
    values:
      layout: "class-index"
      wow_class: "priest"
  -
    scope:
      path: ""
      type: "priest-combinations"
    values:
      layout: "combinations"
      wow_class: "priest"
  -
    scope:
      path: ""
      type: "priest-relics"
    values:
      layout: "relics"
      wow_class: "priest"
      chart_class: "full-height"
      num_ilevel_values: 20
  -
    scope:
      path: ""
      type: "priest-trinkets"
    values:
      layout: "trinkets"
      wow_class: "priest"
      chart_class: "full-height"
  -
    scope:
      path: ""
      type: "rogue"
    values:
      layout: "class-index"
      wow_class: "rogue"
  -
    scope:
      path: ""
      type: "rogue-combinations"
    values:
      layout: "combinations"
      wow_class: "rogue"
  -
    scope:
      path: ""
      type: "rogue-relics"
    values:
      layout: "relics"
      wow_class: "rogue"
      chart_class: "full-height"
      num_ilevel_values: 20
  -
    scope:
      path: ""
      type: "rogue-trinkets"
    values:
      layout: "trinkets"
      wow_class: "rogue"
      chart_class: "full-height"
  -
    scope:
      path: ""
      type: "shaman"
    values:
      layout: "class-index"
      wow_class: "shaman"
  -
    scope:
      path: ""
      type: "shaman-combinations"
    values:
      layout: "combinations"
      wow_class: "shaman"
  -
    scope:
      path: ""
      type: "shaman-relics"
    values:
      layout: "relics"
      wow_class: "shaman"
      chart_class: "full-height"
      num_ilevel_values: 20
  -
    scope:
      path: ""
      type: "shaman-trinkets"
    values:
      layout: "trinkets"
      wow_class: "shaman"
      chart_class: "full-height"
  -
    scope:
      path: ""
      type: "warlock"
    values:
      layout: "class-index"
      wow_class: "warlock"
  -
    scope:
      path: ""
      type: "warlock-combinations"
    values:
      layout: "combinations"
      wow_class: "warlock"
  -
    scope:
      path: ""
      type: "warlock-relics"
    values:
      layout: "relics"
      wow_class: "warlock"
      chart_class: "full-height"
      num_ilevel_values: 20
  -
    scope:
      path: ""
      type: "warlock-trinkets"
    values:
      layout: "trinkets"
      wow_class: "warlock"
      chart_class: "full-height"
  -
    scope:
      path: ""
      type: "warrior"
    values:
      layout: "class-index"
      wow_class: "warrior"
  -
    scope:
      path: ""
      type: "warrior-combinations"
    values:
      layout: "combinations"
      wow_class: "warrior"
  -
    scope:
      path: ""
      type: "warrior-relics"
    values:
      layout: "relics"
      wow_class: "warrior"
      chart_class: "full-height"
      num_ilevel_values: 20
  -
    scope:
      path: ""
      type: "warrior-trinkets"
    values:
      layout: "trinkets"
      wow_class: "warrior"
      chart_class: "full-height"


exclude:
  - .editorconfig
  - Gemfile
  - Gemfile.lock
  - devserve.bat
  - README.md
  - ViewsGenerator.rb
  - assets/img/src
  - assets/js/src
  - data/meta

plugins:
  - jekyll-sitemap # Generate the sitemap.xml
  - jemoji # Enable GitHub emojis

repository: SimCMinMax/herodamage # GitHub Pages metadata
wow_classes: [death_knight, demon_hunter, druid, hunter, mage, monk, paladin, priest, rogue, shaman, warlock, warrior]
